### ISSUE TITLE
Ipopt website down

### ISSUE THREAD

**Issue by Cody-G** [JuliaOpt/Ipopt.jl#104]
The Ipopt download has been failing for a few days when installing Ipopt.  The whole coin-or.org website seems to be down.  Hopefully this is just temporary?

**Comment by mlubin** [comment]
I'm assuming that you're on linux and have Ipopt.jl 0.3.0 installed, because the install for other platforms doesn't depend on the coin-or website. Try this fix. In your local copy of Ipopt.jl, change the line
https://github.com/JuliaOpt/Ipopt.jl/blob/ac35cedbdd602bb0f1c257a5e04b516df5119155/deps/build.jl#L10
to
```julia
use_BinaryProvider = true
```
and then run `Pkg.build("Ipopt")`.

**Comment by Cody-G** [comment]
Ah yes that worked, thanks for your quick response!

**Comment by Non-Contradiction** [comment]
This problem also affects other solvers like Cbc.jl. Maybe github mirror like <https://github.com/coin-or/Ipopt> and <https://github.com/coin-or/Cbc> could be used if the coin-or website doesn't work?

**Comment by mlubin** [comment]
I'll accept a PR that switches the download from coin-or.org to the tars hosted on github.

**Comment by tkelman** [comment]
the github repos are missing the svn externals structure though so require additional pieces

**Comment by tkelman** [comment]
Going through cache.julialang.org would be straightforward though.
