### ISSUE TITLE
Ipopt is not working with a constraint having combination of two square terms of unknown variables in the denominator 

### ISSUE THREAD

**Issue by mamuniut09** [JuliaOpt/Ipopt.jl#169]
The Ipopt is not working with a constraint having combination of two square terms of unknown variables in the denominator. The code and the error message are given below. It would be highly appreciated if anyone could solve the issue.
 
**Code**:
```Julia
using JuMP, Ipopt
a=zeros(3,1,3); b=zeros(3,1,3);
a[:,1,1]=[4; 5; 6]; a[:,1,2]=[5; 6; 7]; a[:,1,3]=[5; 6; 8]; 
b[:,1,1]=[1; 2; 3]; b[:,1,2]=[4; 5; 6]; b[:,1,3]=[4; 6; 8];

m = Model(with_optimizer(Ipopt.Optimizer))
@variable(m, v[1:3, 1, 1:3]);
@variable(m, r[1:3, 1, 1:3]);
@variable(m, p[1:3, 1, 1:3]);

for i=1:3
    @NLconstraint(m, [j=1:3], v[j,1,i]==a[j,1,i]/(r[j,1,i]^2+p[j,1,i]^2));
    @NLconstraint(m, [j=1:3], r[j,1,i]==a[j,1,i]/(a[j,1,i]^2+b[j,1,i]^2));
    @NLconstraint(m, [j=1:3], r[j,1,i]==p[j,1,i]);
end

@objective(m,Min,0);
optimize!(m)
```
**Error message:** EXIT: Invalid number in NLP function or derivative detected.

(Edit: odow: formatting)

**Comment by odow** [comment]
The issue is that nothing is stopping the denominator from going to zero, leading to a divide-by-zero error (i.e., your problem is non-differentiable.) You will need to re-formulate your problem.

In future, you can use discourse for questions like this: https://discourse.julialang.org/c/domain/opt

If you search for "Invalid number in NLP function," you can find that this question has been asked and answered before: https://discourse.julialang.org/t/error-with-ipopt/20989

**Comment by mamuniut09** [comment]
Thank you so much.
