### ISSUE TITLE
Ipopt.jl: LibIpopt issues on Mac

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaOpt/Ipopt.jl#33]
I am just getting into using/learning Julia and I tired adding the IPOPT.jl package. It installed just fine but when I tried testing it.. it gave me a libipopt error :

Pkg.test("Ipopt")
INFO: Testing Ipopt
ERROR: LoadError: LoadError: UndefVarError: libipopt not defined
 in createProblem at /Users/arora/.julia/v0.4/Ipopt/src/Ipopt.jl:182
 in include at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in include_from_node1 at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in include at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:129
 in process_options at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in _start at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
while loading /Users/arora/.julia/v0.4/Ipopt/test/hs071_test.jl, in expression starting on line 114
while loading /Users/arora/.julia/v0.4/Ipopt/test/runtests.jl, in expression starting on line 5

etc...

I also tried running the provided test examples, same result..

Any thoughts on how to go about fixing this issue? I have used IPOPT before but that was complied from source as I was programming in C, FORTRAN.

thanks a lot.

**Comment by tkelman** [comment]
What happens if you run `Pkg.build("Ipopt")` ?

**Comment by GravityAssisted** [comment]
Seems to go just fine:

Pkg.build("Ipopt")
INFO: Building Homebrew
HEAD is now at f52c5f1 Update test dependencies
HEAD is now at 885ba65 Merge pull request #40 from staticfloat/staging
INFO: Building Ipopt

WARNING: deprecated syntax "[a=>b, ...]" at /Users/arora/.julia/v0.4/Ipopt/deps/build.jl:72.
Use "Dict(a=>b, ...)" instead.

**Comment by GravityAssisted** [comment]
When I run the test script outside REPL. I got:

dyld: lazy symbol binding failed: Symbol not found: _MPI_Init
  Referenced from: /usr/local/lib/libipopt.dylib
  Expected in: flat namespace

dyld: Symbol not found: _MPI_Init
  Referenced from: /usr/local/lib/libipopt.dylib
  Expected in: flat namespace

Trace/BPT trap: 5

This looks like a flat-namespace issue on Mac OSX. Maybe I need to recompile the binary and then use inside Julia ?

**Comment by tkelman** [comment]
What does the file `/Users/arora/.julia/v0.4/Ipopt/deps/deps.jl` say? It looks like it's picking up a previously compiled version of ipopt which is trying to use the MPI version of Mumps (which isn't going to work well). You could maybe do `brew unlink ipopt`, re-run `Pkg.build("Ipopt")` then hopefully it would download the for-use-with-Julia version of Ipopt instead of the homebrew-science one.

**Comment by GravityAssisted** [comment]
This is what the deps.jl file has:

macro checked_lib(libname, path)
    ((VERSION >= v"0.4.0-dev+3844" ? Base.Libdl.dlopen_e : dlopen_e)(path) == C_NULL) && error("Unable to load \n\n$libname ($path)\n\nPlease re-run Pkg.build(package), and restart Julia.")
    quote const $(esc(libname)) = $path end
end

@checked_lib libipopt "/usr/local/lib/libipopt.dylib"

I will try the brew unlike tomm. morning and get back to you. But I did not install Ipopt using brew before (just did a make on the source ) and I just installed the brew package manager recently. 

thanks a lot !

**Comment by tkelman** [comment]
Okay, if your locally compiled version is not from homebrew then the cleanest way of removing it would be finding the original source build and running `make uninstall` from there. I think there is a stub standin for MPI in the sequential build of mumps but I'm not sure what's going wrong here.

You might also get away with temporarily renaming `/usr/local/lib/libipopt.dylib` to something else, to force `Pkg.build("Ipopt")` to download its own version.

**Comment by GravityAssisted** [comment]
You are correct, I am linking to the old version of libipopt. 
Looks like MPI was the culprit like you pointed out. But I was still getting errors after renaming the default `libipopt` library so then I commented out the Homebrew specific lines 
```
@osx_only begin
    using Homebrew
   provides(Homebrew.HB, "ipopt", libipopt, os = :Darwin)
end
```
in Build.jl inside Ipopt directory ( `/Users/arora/.julia/v0.4/Ipopt`) and again ran `Pkg.build("Ipopt")`.

Everything worked then including the examples!  thanks for all the help :+1:  

Maybe there should be a way to bypass Homebrew if it is not working and just compile from the source ?

**Comment by tkelman** [comment]
What was the problem when you didn't have the homebrew provider commented out? You more or less found the "way to bypass Homebrew" here.

**Comment by GravityAssisted** [comment]
It was always relinking with Homebrew (when I unlinked it). I think the issue mite be that I had a previous compiled version of Ipopt installed and that was confusing Homebrew. I am not sure though. 

Do you want me to close this ?

**Comment by tkelman** [comment]
To clarify a little, when you do `Pkg.build("Ipopt")`, or for other packages that use https://github.com/JuliaLang/Homebrew.jl to manage binary dependencies on OS X, it's actually using a private sandboxed version of Homebrew that lives inside `Pkg.dir("Homebrew")`, and should be independent of your global system Homebrew installation. So the linking there won't be to a globally visible system-wide location like `/usr/local`, it will be inside `/Users/arora/.julia/v0.4/Homebrew/usr` or something similar.

Your system-wide homebrew was actually not the problem here at all, rather it was that when a pre-existing copy of the ipopt library was found, BinDeps decided to use that instead of downloading a new binary.

**Comment by GravityAssisted** [comment]
Ahh, I see, I wasn't aware of that. Thanks for the clarification. I do see that Ipopt directory in the Julia specific Homebrew. Not sure why BinDeps decided to use the `/usr/local/lib` copy of the library.

Will close issue this now. Thank you again.

**Comment by tkelman** [comment]
> Not sure why BinDeps decided to use the `/usr/local/lib` copy of the library.

That's by design (I think). If it finds a library in the default search path that has the same name as what you're looking for, and it passes very basic validation tests (the default test is "can this library be `dlopen`ed", but a more comprehensive validation test might have been able to catch the issue with MPI that you ran into), then it assumes you wanted to use that version. Some people will want to use a custom-compiled version of the Ipopt library with the Julia package, and I don't think we should rule out that use case, but it has seemed to lead to problems for multiple users now.

**Comment by GravityAssisted** [comment]
I see, is it possible to somehow tell the story kg.

**Comment by GravityAssisted** [comment]
I see,  is it possible to tell `BindDeps` via the `Pkg.add` command whether to use a custom build Ipopt or not? I am new to Julia so am not aware of some of it's features yet.

**Comment by tkelman** [comment]
Not that I know of. Neither `Pkg.add` or `Pkg.build` have any optional arguments, except for a version number in the case of `Pkg.add`.
