### ISSUE TITLE
Error: package coinmumps was not found in the pkg-config search path

### ISSUE THREAD

**Issue by rajhanschinmay** [JuliaOpt/Ipopt.jl#38]
Getting error,

Package coinmumps was not found in the pkg-config search path.
Perhaps you should add the directory containing `coinmumps.pc'
to the PKG_CONFIG_PATH environment variable

can anyone help?

**Comment by tkelman** [comment]
You probably need to install `pkg-config` first. Remove `~/.julia/v0.3/Ipopt/deps/src` and `~/.julia/v0.3/Ipopt/deps/usr` before trying `Pkg.build("Ipopt")` again.

**Comment by rajhanschinmay** [comment]
pkg-config is already installed.
I have mumpc installed. But is seems to be not detecting it. How to install it/

**Comment by tkelman** [comment]
Currently the package isn't really designed to use a pre-installed version of mumps, and since the configuration of mumps from distributions varies pretty widely this isn't an easy configuration to support. Can you please elaborate with as many details about your system, steps of exactly what you're running, and output of what happens vs what you expected as you can? You're making us guess exactly what you're trying to accomplish and where the problem lies, until you can provide more information.

**Comment by rajhanschinmay** [comment]
ok, np.
I am trying to install IPOPT. This needs MUMPS.
So as suggested in its procedure, I tried installing it.
But when I am running make command of IPOPT, it is saying 'coinmumps' is needed, but not found.
I am using Linux Ubuntu 14.04 LTS, 32 bit OS.

**Comment by tkelman** [comment]
If you're building just the C++ Ipopt library by hand and not intending to use it through this Julia package, this is the wrong repository to file this issue. You also send a message to the Ipopt mailing list which is the proper place for the question, if you aren't using Julia at all.
